version: "3.9"
services:
    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: db-container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
            MYSQL_USER: dogiahuy
            MYSQL_PASSWORD: 17062003
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:

