version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 17062003
      MYSQL_DATABASE: sampleDB
      MYSQL_USER: dogiahuy
      MYSQL_PASSWORD: 17062003
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
